# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "free-shipping"
client_id = "9575bc8193bcfa21f1b748890ddca599"
application_url = "https://techno-flexibility-writers-yesterday.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://techno-flexibility-writers-yesterday.trycloudflare.com/auth/callback",
  "https://techno-flexibility-writers-yesterday.trycloudflare.com/auth/shopify/callback",
  "https://techno-flexibility-writers-yesterday.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ninjatech-demo.myshopify.com"
